nodeLinker: pnp

packageExtensions:
  '@wordpress/block-editor@*':
    dependencies:
      react: "^17.0.0"
      react-dom: "^17.0.0"
      reakit-utils: "^0.15.1"
      redux: "^4.1.0"
  '@wordpress/components@*':
    dependencies:
      react: "^17.0.0"
      react-dom: "^17.0.0"
      redux: "^4.1.0"
  '@wordpress/blocks@*':
    dependencies:
      redux: "^4.1.0"
  '@wordpress/rich-text@*':
    dependencies:
      redux: "^4.1.0"
  '@wordpress/keyboard-shortcuts@*':
    dependencies:
      redux: "^4.1.0"
  '@wordpress/notices@*':
    dependencies:
      redux: "^4.1.0"
  '@wordpress/data@*':
    dependencies:
      react: "^17.0.0"
      react-dom: "^17.0.0"
  '@wordpress/core-data@*':
    dependencies:
      redux: "^4.1.0"
  '@wordpress/eslint-plugin@*':
    dependencies:
      '@babel/core': "^7.0.0-0"
  '@wordpress/compose@*':
    dependencies:
      react: "^17.0.0"
  '@wordpress/scripts@*':
    dependencies:
      '@babel/core': "^7.0.0-0"
  '@wordpress/jest-preset-default@*':
    dependencies:
      react: "^17.0.0"
      react-dom: "^17.0.0"
      '@babel/core': "^7.0.0-0"
  '@wordpress/postcss-plugins-preset@*':
    dependencies:
      postcss: "^8.1.0"
  react-with-styles@*:
    dependencies:
      react-dom: "^17.0.0"
  reakit-warning@*:
    dependencies:
      react-dom: "^17.0.0"
